"""import_username_directory_schema

Revision ID: 32b7555a6f3c
Revises: 
Create Date: 2026-09-20 13:32:05.633041
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '32b7555a6f3c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('username',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('initial_letter', sa.String(length=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_username_initial_letter'), 'username', ['initial_letter'], unique=True)
    op.create_index(op.f('ix_username_username'), 'username', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_username_username'), table_name='username')
    op.drop_index(op.f('ix_username_initial_letter'), table_name='username')
    op.drop_table('username')
    # ### end Alembic commands ###
